name: CF CI

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
    branches:
      - 3.x
      - 4.x-unstable
      - 4.x
      - 5.x
      - 6.x

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Upload to CurseForge
        run: ./gradlew build curseforge --stacktrace
        env:
          danielshe_curse_api_key: ${{ secrets.CF_API_KEY }}
          BRANCH_NAME: ${{ github.ref }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}